### ISSUE TITLE
issue with src module

### ISSUE THREAD

**Issue by OtherwisePitt** [rudymohammadbali/ctk_components#2]
if simply folder downloaded into direct of my project, i got error " no module nam src"

**Comment by rudymohammadbali** [comment]
Could you share error message here?

**Comment by OtherwisePitt** [comment]
the error:
File "c:\Users\pisc\Desktop\Nuova cartella (4)\ricerca_cliente.py", line 13, in <module>
    from ctk_components import *
  File "c:\Users\pisc\Desktop\Nuova cartella (4)\ctk_components\__init__.py", line 29, in <module>
    from .ctk_components import CTkAlert
  File "c:\Users\pisc\Desktop\Nuova cartella (4)\ctk_components\ctk_components.py", line 36, in <module>
    from src.util.CTkGif import CTkGif
ModuleNotFoundError: No module named 'src'

the code:import tkinter
from tkinter import ttk
import tkinter as tk
import customtkinter
from PIL import Image
from CTkTable import *
from CTkTableRowSelector import *
from CTkMessagebox import CTkMessagebox
import os
import sqlite3
import add_clienti
import add_destinazione
from ctk_components import *



cod_cliente_entry = None
mastro_entry = None
rag_soc1_entry = None
rag_soc2_entry = None
indirizzo_entry = None
comune_entry = None
cap_entry = None
cf_entry = None
ctkentry10 = None
piva_entry = None
sdi_entry = None

customtkinter.set_appearance_mode("System")
customtkinter.set_default_color_theme("dark-blue")

HEIGHT = 720
WIDTH = 1000



def ricerca(event):
    search_text = cerca_entry.get().lower()
    tree.delete(*tree.get_children())  # Rimuove tutte le righe attualmente presenti nel Treeview
    cursor.execute("SELECT * FROM anag_clienti")
    rows = cursor.fetchall()
    for row in rows:
        if any(search_text in str(value).lower() for value in row):
            tree.insert("", "end", values=row[:15])

      # CTkNotification
    CTkNotification(master=root, state="info", message="message", side="right_bottom") # This will display a notification at the right bottom of the app.  

i have downloaded and extracted the folder and placed it in "c:\Users\pisc\Desktop\Nuova cartella (4)"

**Comment by rudymohammadbali** [comment]
Check the directory structure:

```
Nuova cartella (4)
│
└───ctk_components
│   │   __init__.py
│   │   ctk_components.py
│
└───src
    └───util
        │   CTkGif.py
```

if not work try installing from PyPi:

```
pip install ctkcomponents
```

Usage:

```python
import ctkcomponents

ctkcomponents.CTkNotification(master=root, state="info", message="message", side="right_bottom")
```
