### ISSUE TITLE
Documentation error: CTkProgressPopup.update_progress() takes only float values from 0.0 to 1.0

### ISSUE THREAD

**Issue by Thosch42** [rudymohammadbali/ctk_components#3]
First things first: Nice job!!!
These are the little things, making live easier.

I found a little error in the documentation of the ProgressPopup. The .update_progress() method takes only float values in the range 0.0 to 1.0 and not as stated integers from 0 to 100.

Best regards
Thomas

**Comment by rudymohammadbali** [comment]
Thanks ☺️
